name: SAP
services:
  database:
    container_name: SAP-data
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - "$PWD/database/data/db:/data/db"
    ports:
      - 27018:27017
    networks:
      default:
        ipv4_address: 172.18.0.2

  SAP_api:
    container_name: sap-api
    image: node:lts-alpine
    restart: unless-stopped
    depends_on:
      - database
    volumes:
      - "$PWD:/app"
    working_dir: "/app"
    command: ["npm", "run", "dev"]
    environment:
      - PORT=8080
      - DATABASE_HOST=SAP-data
      - DATABASE_PORT=27017
      - DATABASE_NAME=SAP-data
    networks:
      default:
        ipv4_address: 172.18.0.3
      proxy-network:
        ipv4_address: 172.20.0.4

networks:
  default:
    name: teamwork
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24
          gateway: 172.18.0.1
  proxy-network:
  
    external: true
    name: proxy-network