name: project_backend
version: "3"
services:
  database:
    image: mongo
    container_name: school-administration-system-data
    restart: unless-stopped
   
    ports:
      - "27018:27017"
    volumes:
      - ./data:/data/db
    networks:
      - mongodb_network
  
networks:
  mongodb_network:
   driver: bridge